# Generated by Django 2.1.7 on 2020-12-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.CharField(max_length=20)),
                ('questionData', models.CharField(max_length=40)),
                ('answerData', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ChatbotUI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('data_id', models.CharField(max_length=20)),
                ('userQuestion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('univname', models.CharField(max_length=20)),
                ('major', models.CharField(max_length=20)),
                ('grade', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=20)),
                ('birth', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('univname', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=30),
        ),
    ]
